### ISSUE TITLE
4.4.x tags are not related to 4.4 branch, and do not contain new code

### ISSUE THREAD

**Issue by willmurnane** [vert-x3/vertx-consul-client#107]
### Version

Version 4.4.4 doesn't include the changes to the 4.4 branch. See the history [here](https://github.com/vert-x3/vertx-consul-client/commits/4.4.4); no changes have propagated from 4.4 into released tags since 4.4.1.

### Context

I am trying to use the new ACL API, and noticed that the consul client was still calling the old endpoint. This is [fixed in the 4.4 branch](https://github.com/vert-x3/vertx-consul-client/blob/4.4/src/main/java/io/vertx/ext/consul/impl/ConsulClientImpl.java#L459) but [still has the old endpoint in 4.4.4](https://github.com/vert-x3/vertx-consul-client/blob/4.4.4/src/main/java/io/vertx/ext/consul/impl/ConsulClientImpl.java#L295). 

Also note that [the version number set in the pom in 4.4 is 4.4.1-SNAPSHOT](https://github.com/vert-x3/vertx-consul-client/blob/4.4/pom.xml#L12).

### Do you have a reproducer?

No

### Steps to reproduce

```
mkdir tmp; cd tmp
curl -O https://repo1.maven.org/maven2/io/vertx/vertx-consul-client/4.4.4/vertx-consul-client-4.4.4.jar
unzip vertx-consul-client-4.4.4.jar
# The 4.4.4 release still contains the old URL for creating ACL tokens
javap -v io/vertx/ext/consul/impl/ConsulClientImpl.class | grep 'v1/acl/create'
```

**Comment by vietj** [comment]
those change have been done in master and not back ported to 4.x branch (https://github.com/vert-x3/vertx-consul-client/commits/4.x) . Feel free to open PR to backport them, they will be part then of 4.4.5

**Comment by ViktoriiaLebedeva** [comment]
Hi. I will transfer all the latest changes from master to 4.x. After that, it will be possible to release a version 4.4.5 with latest changes

**Comment by willmurnane** [comment]
Thanks, everyone, for making the relationship between the branches clear, and volunteering to implement the changes. I found one more minor change that I think should be applied, and left a comment on PR108. There's another instance of the old ACL endpoint [in the current `master`](https://github.com/vert-x3/vertx-consul-client/blob/master/src/main/java/io/vertx/ext/consul/impl/ConsulClientImpl.java#L271) and [4.x](https://github.com/vert-x3/vertx-consul-client/blob/4.x/src/main/java/io/vertx/ext/consul/impl/ConsulClientImpl.java#L572) branches. I would be happy to make the change, or to let someone else do it. Thank you 😸

**Comment by ruslansennov** [comment]
Hi @willmurnane 
PRs are welcome :)

**Comment by willmurnane** [comment]
Viktoriia explained that the reason for the old endpoint is to support the old API as well, and the method is marked deprecated in the interface, so the changes made are all that's desirable to make. The changes made in #108 are thus sufficient, and I'll close this issue. Thanks for the prompt turnaround :)
