### ISSUE TITLE
WebClient not use in same Verticle or thread with self create 

### ISSUE THREAD

**Issue by coverdh** [vert-x3/vertx-consul-client#32]
WARN Reusing a connection with a different context: an HttpClient is probably shared between different Verticles
http://vertx.io/docs/vertx-core/java/#_httpclient_usage

WebClient  same
....

**Comment by ruslansennov** [comment]
Hi @coverdh 
Could you provide a small reproducer?

**Comment by vietj** [comment]
this likely happens because the the consul client is shared between different threads, you can avoid this by using a Verticle for your code.

**Comment by coverdh** [comment]
@vietj  I avoided the problem in this way ,Thanks

**Comment by coverdh** [comment]
@ruslansennov I use webclient to reproduce the problem in a high load environment, which is also reflected in the webclient documentation.
But the consul-client I did not reproduce in the test environment, the production environment will occasionally report the WARN

**Comment by ruslansennov** [comment]
@coverdh is it possible to check latest snapshot version int your environments?

**Comment by ruslansennov** [comment]
released
