### ISSUE TITLE
Can't set port of client.

### ISSUE THREAD

**Issue by AshleyByeUK** [vert-x3/vertx-consul-client#33]
I'm trying to figure out how to set the port of the consul client. The client always uses a random port to communicate with consul. How do I set the port of the client to a value I want (`setPort(1234)` only seems to register the service on port 1234, but it listens on something wildly different)?

So for instance, in the consul log I see the following when I register my service:
`2017/07/06 21:59:19 [DEBUG] http: Request PUT /v1/agent/service/register (649.447µs) from=127.0.0.1:53469`. If I restart the service, I then get `2017/07/06 22:04:59 [DEBUG] http: Request PUT /v1/agent/service/register (629.041µs) from=127.0.0.1:53758`. What I want is for the request to come from the same pre-determined port.

I've had a look through the source code and can't see any obvious way to do this. I've even tried to get the value of the port that is going to be randomly chosen but can't figure that out either, although this would not be an ideal solution as I'd like to have the port pre-determined as it's going to be running in a docker container and I need to configure mappings. I'd appreciate any advice.

**Comment by ruslansennov** [comment]
You shouldn't set outgoing port in your app (you're right, it defines by random), as well as mapping outgoing ports in docker configs. All should work out-of-box.
Note that `ConsulClientOption.setPort()` method sets remote incoming port of consul client

**Comment by AshleyByeUK** [comment]
Thanks. I finally figured out what was going on. I think part of the problem is being new to consul and still getting to grips with vertx too. The main problem I was trying to solve was health checks, but I'm now running a `HttpServer` in a separate verticle and that does the job nicely (I think I was expecting the consul client to do some magic under the hood and set that up on the specified port). Anyway, all solved now :-D
