### ISSUE TITLE
Request method for deregister operation

### ISSUE THREAD

**Issue by deedarb** [vert-x3/vertx-consul-client#42]
https://github.com/vert-x3/vertx-consul-client/blob/77a3b5de3cc1f65a8cd66935caae8e19b71ea177/vertx-consul-client/src/main/java/io/vertx/ext/consul/impl/ConsulClientImpl.java#L290

this line should use PUT method as mentioned here https://www.consul.io/api/catalog.html#deregister-entity

consul version: 'v1.0.0'
vertx version: '3.5.0'

**Comment by ruslansennov** [comment]
@deedarb thanks for reporting
This bug did not appear until version `1.0.0`
