### ISSUE TITLE
Can't supply service's metadata while registering a new service.

### ISSUE THREAD

**Issue by romalev** [vert-x3/vertx-consul-client#50]
Based on the consul documentation portal while registering a new service -> there's also an opportunity to supply metadata: https://www.consul.io/api/agent/service.html#register-service.

As far as I understand (based on looking at the current vertx consul client impl) there's no way to supply arbitrary KV metadata that would get linked to the service instance. 

`JsonObject jsonOpts = new JsonObject()
      .put("ID", serviceOptions.getId())
      .put("Name", serviceOptions.getName())
      .put("Tags", serviceOptions.getTags())
      .put("Address", serviceOptions.getAddress())
      .put("Port", serviceOptions.getPort());`

Is it something that wasn't done in purpose ?

**Comment by ruslansennov** [comment]
You're right, meta support is not implemented yet. PRs welcome
