### ISSUE TITLE
Can't specify lock delay as 0s while creating session.

### ISSUE THREAD

**Issue by romalev** [vert-x3/vertx-consul-client#56]
From java docs: 

> Lock delay is a time duration, between 0 and 60  seconds. When a session invalidation
> takes place, Consul prevents any of the previously held locks from being re-acquired
> for the lock-delayi nterval. The default is 15s.

Now if we look at the https://github.com/vert-x3/vertx-consul-client/blob/master/src/main/java/io/vertx/ext/consul/SessionOptions.java

we see : 

```
public JsonObject toJson() {
    JsonObject jsonObject = new JsonObject();
    if (lockDelay != 0) {
      jsonObject.put(LOCK_KEY, lockDelay + "s");
    }
  // rest of the code...  
}
```

Consul itself allows us to specify 0s as a lock delay - this works just fine: 
curl -X PUT -d '{"LockDelay":"0s","Name":"client7-lock","Node":"WP2491","Checks":[],"Behavior":"delete", "TTL":"10s"}' 'http://localhost:8500/v1/session/create'

**Comment by ruslansennov** [comment]
@romalev thanks for the report. Could you make a PR to fix this?

**Comment by ruslansennov** [comment]
Thank you!
