### ISSUE TITLE
Watch key value timeout

### ISSUE THREAD

**Issue by phamtai97** [vert-x3/vertx-consul-client#70]
Hi @vietj 
I use the feature to `Watch` key value for my project. Then, I have timeout problem  when i watch key-value.  I set timeout for a request is 10s. This is error:

```sh
io.vertx.core.http.impl.HttpClientRequestBase$1: The timeout period of 10000ms has been exceeded while executing GET /v1/kv/xxxxxx?wait=10m&index=226870
```

My code:
```java
  Watch<KeyValue> watch = Watch.key(key, this.vertx, this.consulClientOptions);

    watch
        .setHandler(
            res -> {
              if (res.succeeded()) {
                if (ValidateUtil.notNull(res.prevResult())) {
                  callback.onChange(res.nextResult().getKey(), res.nextResult().getValue());
                }
              } else {
                LOGGER.error(res.cause());
              }
            })
        .start();
```

Can you help me explain this problem?

**Comment by ruslansennov** [comment]
Hi @phamtai97 
I guess you set `ConsulOptions`'s timeout to 10s which is less than blocking awaiting time. In this case, you will receive such errors along with successful events, and this is expected behavior. The bad news: after each timeout error, each next resubscribing will be invoked with a progressive delay (up to 180s).
I believe we should ignore all timeout exceptions with resubscribing without any delay. I'll prepare a patch soon.

**Comment by phamtai97** [comment]
Thank you @ruslansennov.
I can not set ConsulOptiont's timeout too hight. Because I also call Consul for other APIs.

**Comment by phamtai97** [comment]
Which version did you release?

**Comment by ruslansennov** [comment]
it will be 4.0.0

**Comment by phamtai97** [comment]
But In version > 3.8, Some api of vertx have been changed. I think we only need have patch version such as 3.7.3.

**Comment by VoxT** [comment]
Same issue too.
We are using vertx 3.7.1 in production and have to upgrade to version 4.0.0 with a bunch of change is not reasonable.
Can you provide a patch version ?

Thank you.

**Comment by phamtai97** [comment]
@ruslansennov help me !!!. thanks

**Comment by ruslansennov** [comment]
@vietj are there any plans to release version 3.8.6?

**Comment by phamtai97** [comment]
Oh @ruslansennov , I think that we only need a patch version less V3.8.

**Comment by ruslansennov** [comment]
i'm afraid it is impossible

**Comment by ruslansennov** [comment]
cherry-picked to `3.9` branch

**Comment by ruslansennov** [comment]
cherry-picked to `3.8` branch
