### ISSUE TITLE
How to connect Consul cluster

### ISSUE THREAD

**Issue by phamtai97** [vert-x3/vertx-consul-client#73]
Hi all.
I deploy Consul following the cluster model (3 nodes). So how to connect the vertx-consul-client to the cluster?

**Comment by ruslansennov** [comment]
just connect it to one of the nodes

**Comment by phamtai97** [comment]
Oh, so if the node has died ??? Can I deploy Consul agent mode client to connect to Consul cluster, then I use vertx-consul-client connect to Consul agent ?

**Comment by ruslansennov** [comment]
You must start your own instance of the consul working in agent mode. You should send your requests to the consul agent, not the consul server, this is a normal scenario. In any case, vertx-consul-client does not intend to select a host from the list

**Comment by phamtai97** [comment]
oh, thanks for your support. I will try it.
